# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "sandbox_test_launcher"
edition.workspace = true
rust-version.workspace = true

[dependencies]
sandbox.workspace = true

anyhow.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
nix = { workspace = true, features = ["sched", "user"] }

[lints]
workspace = true
